name: auto-release

on:
  release:
    types: [published, edited]

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
      - name: printenv
        run: env
      - name: tag
        run: echo ${{ github.ref }}
